language: node_js
dist: trusty
git:
  depth: 1
cache:
  edge: true
  directories:
    - node_modules
    - "$(npm root -g)"
    - "$(npm config get prefix)/bin"
branches:
  only:
    - master
    - stage
    - test
    - dev
env:
  global:
    # CODECLIMATE_REPO_TOKEN=[secure]
    - secure: "qb4mYf5Ki8hGIBQMB5zSe+2QiF4WmVM0pLW7g+mF2c89RElum1NhJgU4B92KGoS8MndHL72dcvR6s1BJbQiVueeAdJO6UHvjMsd/3RJ39n/DuwrkcFxO0OpdXzmkq6El/zijR0yRpdNEcRMrE799mndKO/Kje1O+yl2epIfOmerVKky17n662Ns/6JIqWHPyqjMIu80mg2QyUW1oW0wnSUfE4oNDOP3aO8AzlQdfxc4KffEhIpsyNYakcsZaeiOMyF3nV2IM13KMQcsTtmPN1HcnvE7Bxi1mOpIIbj0SJ3aFr1U8yX3C9j9YRjmCR+zH/09CYtfsby73BKKT1egtXQbTwDUEdiYyK/pRGQsXT1lc3IardvKHgNBTqn7oSiWkAY6NTBmPX4mMe3S11tfqa5UYJV8gKSe0YkkRDOe3WAt9pG8g3SP3mwj1rPl6aoFqpKbIPljQ24rTPhizA29FgL/WdM7LHwkh5kYBSL3RPDRnbAORvdQiKZfQPrS/FsN1D/pokROKghmix1E5dTl/Rr7UmfvK2h8IeX/BT0m8NRoEMLQB1J1pfEFnP1rE9tFiMNYYJUelIA7aXqhcGSvMV1VRuWo7nMuU5e/yW0jsnC0YeDPpj6hdWWsUGfifpt+BjrIToXWhGljoZVLZ+Wiuts61pK/lmTOfUWJ7eBvKkRY="
    # AWS_DEFAULT_REGION=[secure]
    - secure: "BgY9xbCYaVsJ7uZ4Oxxo6FzilGXEtCo56SuyYJTgXSBxA50mCig02VqPVwLMM2rftNYkX5q1q6DRP7SZmtz7/0wfR67btRiDlQBu8W2cosCsAokeARq0dd+MuybcyrdxLs3tlRLLYPRgvKpdDeXKIxTfAVqqH3++YciVab2hw2xcnTijSGXHH+KTs6Ly/Xb9wUO6NpC8rNqzDrsAeYpoePKLH2PEO0Zq0vKz3wjuisDQiQol6wNUWxhJU95GFl/b8Ctp91thobQmtalTZQDE72uNMJUY9g/JIiJVZhxQOMQD+y+O5olKwtG2pcBFnOet+vzn10aLOuhjiVjpz4V2W4CZ5vaURYNUspTZjbPkwsaCedLxjNmwuz73+ME5BkJMGhJKkXC0NMlAEZi7xuiXdYWKNuGyRkXSaHzjnkKcLQad6GIzmYEK2C8aQ+rjpPP7xUomIWlvZuLUQOhJCyZktIX4yXjCEP0xytc13eUXza+RQxDePI3JibFzs4lZ/0Td+QtP85Rnt8zeN+q8+FzxYDLf5b51gn/OmoKTmupzrbTHmJSVDaxJB5opWwzBt8gpBAN/dw1fJpLFfyKl7+PMaqNmgfC0Tmo/Tk0WMXKpT8eXZpJ2U5iItEU49cbb1LglVc2l8N5aPlxEoK2Eb95E5zqvw3r4ySWbgwHAI6lMw+Q="
    # AWS_ACCESS_KEY_ID=[secure]
    - secure: "oFnBYHUQHSkN3MFb+B9up2RotLhgleJskqy38eX1XIoKMp7TRrIXnDfwIZ/wo3/f/uYpl3QGM/lXWR3MYmT4LxzqBRdPJjunfQ0V+bGBCzSPyDDK3JNHPJKExTb4ya/hM7BSWHyhIa0aAXkPSwRRqD3dWXm+ycmeQ2ZPOx24VQEG9tHfZ/0ffS9p7nxITs0ZW03kC8ZnwI5ImDV0DNup1zKuBQd/4WhaKOgKpnpKRpo9OfeTKU2qKXnkzq4JLs6wigiYlJBLdTL2ID8YatLarZ9hiWezPmi2BC/xNw0m4K99GqIOod+WLOKeUqOkvrfAnoYaFZ1r3T4Qvoa70PSyM6vnegNv/PzdQy+Co8JjF3nGn3jPmiMCSOweFZ4EvJgQaqzjxZu1p2UShSuctEr/leQK9mce+MqeWLTpszn7iw0L+jxxm7lrCscfBiNn+GbfDypx1yli3IeI14aslyjatHai1AKssCLCTPIa+2WOzCNwtbRDgOF6KJ1KRANot+PD/dniD8EnnwOtGatacOBQqlNlxKEClPpm1zjCPX/1ebDlibcx70200e9mDaKLUtAUwgi1VPSQQMrRIe4gIOEjxvpBI/M4D5w5OEB6IRUAU7Vx4mVf9uOspCkduhnWzv1dvAu1Tf3opZkXEzmjxc1pGfn/QGvxqErxZTZueiABma4="
    # AWS_SECRET_ACCESS_KEY=[secure]
    - secure: "k9uFsohOEAZ6T0Fmgm6JtGqj7q2RGh9e9cklaQmVsNUpIk1LxfCrAE9TWIpe+sJ7Qn39T9yGZrfNGWw+8pk3at1ZaYMScXg+gwUfS9dnsLOlssIeK0QW71hZXBIYOBC8+31WIhouNq6LBkuFDDavrrn/IcewnY+dkSxE9rqAk1I8CdFL8TCEHF22zVkBmydeInpQD5R60QKnEJpicoMFbWkSaHah98GkXveGnvOzp1Y4nci4LNsPi3lPcLOfK6pyzQzFh++xtGFPx5qx9jjPOWF1dbFm0Pdfb0EDFYm7DwOb4F5Nk/mJy3AuLnICC5cMIlWrPRYslPJidqkbgrjYqY57QdWGWNSI2S8s2aj2/ncHCjzzTTh8ynQZJ3TQxOOBv6sv+Avbr2rZkwlghG1O6JgX3QB8/yd9AchOxuRxWf8G/GW5xnTi3RFb5WF1aIHMeKwfLKJAedzItmIy62dEhQvjydF5EPwN8ijV806Nu75oqCVVKSqjjPbyQe3fUYwbmSkUKMuNDtiasPmy8c70dnoXYxUBGiR/nVL81HhpfTwZ6X2aRnDdhjlLHd2DmqLpm6bEVwJZf/06PQZ0+FvolvgjTnkO7a4gr1x2QtRkdR9FtIy5JGcrrG9DPz0QLAB/PaLXw2UMNspnC7nVwsKQ54klvG3H71Ja2SXLYND0Eys="

stage: "Run Unit Tests :clipboard:"
node_js:
  - 6
  - 8
before_install:
  - bash bin/travis-init.sh
script:
  - recink run unit -c recink-codeclimate -c recink-snyk
