language: node_js
dist: trusty
git:
  depth: 1
cache:
  edge: true
  directories:
    - node_modules
    - "$(npm root -g)"
    - "$(npm config get prefix)/bin"
branches:
  only:
    - master
    - stage
    - test
    - dev
env:
  global:
    # CODECLIMATE_REPO_TOKEN=[secure]
    - secure: "qb4mYf5Ki8hGIBQMB5zSe+2QiF4WmVM0pLW7g+mF2c89RElum1NhJgU4B92KGoS8MndHL72dcvR6s1BJbQiVueeAdJO6UHvjMsd/3RJ39n/DuwrkcFxO0OpdXzmkq6El/zijR0yRpdNEcRMrE799mndKO/Kje1O+yl2epIfOmerVKky17n662Ns/6JIqWHPyqjMIu80mg2QyUW1oW0wnSUfE4oNDOP3aO8AzlQdfxc4KffEhIpsyNYakcsZaeiOMyF3nV2IM13KMQcsTtmPN1HcnvE7Bxi1mOpIIbj0SJ3aFr1U8yX3C9j9YRjmCR+zH/09CYtfsby73BKKT1egtXQbTwDUEdiYyK/pRGQsXT1lc3IardvKHgNBTqn7oSiWkAY6NTBmPX4mMe3S11tfqa5UYJV8gKSe0YkkRDOe3WAt9pG8g3SP3mwj1rPl6aoFqpKbIPljQ24rTPhizA29FgL/WdM7LHwkh5kYBSL3RPDRnbAORvdQiKZfQPrS/FsN1D/pokROKghmix1E5dTl/Rr7UmfvK2h8IeX/BT0m8NRoEMLQB1J1pfEFnP1rE9tFiMNYYJUelIA7aXqhcGSvMV1VRuWo7nMuU5e/yW0jsnC0YeDPpj6hdWWsUGfifpt+BjrIToXWhGljoZVLZ+Wiuts61pK/lmTOfUWJ7eBvKkRY="
    # AWS_DEFAULT_REGION=[secure]
    - secure: "BgY9xbCYaVsJ7uZ4Oxxo6FzilGXEtCo56SuyYJTgXSBxA50mCig02VqPVwLMM2rftNYkX5q1q6DRP7SZmtz7/0wfR67btRiDlQBu8W2cosCsAokeARq0dd+MuybcyrdxLs3tlRLLYPRgvKpdDeXKIxTfAVqqH3++YciVab2hw2xcnTijSGXHH+KTs6Ly/Xb9wUO6NpC8rNqzDrsAeYpoePKLH2PEO0Zq0vKz3wjuisDQiQol6wNUWxhJU95GFl/b8Ctp91thobQmtalTZQDE72uNMJUY9g/JIiJVZhxQOMQD+y+O5olKwtG2pcBFnOet+vzn10aLOuhjiVjpz4V2W4CZ5vaURYNUspTZjbPkwsaCedLxjNmwuz73+ME5BkJMGhJKkXC0NMlAEZi7xuiXdYWKNuGyRkXSaHzjnkKcLQad6GIzmYEK2C8aQ+rjpPP7xUomIWlvZuLUQOhJCyZktIX4yXjCEP0xytc13eUXza+RQxDePI3JibFzs4lZ/0Td+QtP85Rnt8zeN+q8+FzxYDLf5b51gn/OmoKTmupzrbTHmJSVDaxJB5opWwzBt8gpBAN/dw1fJpLFfyKl7+PMaqNmgfC0Tmo/Tk0WMXKpT8eXZpJ2U5iItEU49cbb1LglVc2l8N5aPlxEoK2Eb95E5zqvw3r4ySWbgwHAI6lMw+Q="
    # AWS_ACCESS_KEY_ID=[secure]
    - secure: "SQqOy1xLJKzztxEuObC4Yz7MV1v54mph2Riia9dPsuc5h4BHLzy7sHRe2uANjfUQEZx3PXxYrQhqsukxh1fULDKSN4B6+6oLDdlvOurYXAqIdp02VnMtVunkwYDXiHd49gT9MiJX/xDtsrg3BcMSoVbTTWxgJ8bU+UPdG6HLmBv1xmETxQz060OqPvSUSDsXAIXvu9UNfJVBRK66KlT+QUgb7yQb53Q6wzXRZrXzMjj2tyC/nolsVk6S/R9gFoqkNq1/1WyQR/an//quu6zpk1a9lnuyFY0r9peKvvUT96DZTkNNXEM0ZC/CG8zZE51H50TylmjgoDcYZfeju8yeRLW7aeSeOY57/ar8Hankpgar+cua79rtM6l3cu6hzIvbUrR6jPFL1KoC0wRkJx7LdJ1T6E+AZRf2jwBdzdxlgVllVvgIGxrvugVfyzFSjzZY1A1DoY2u+xY0Oi6Hc8WX7TAARZn/qG0hZYI1fBkw+WcsPk6cPRUZ+5V1d4EFEL/nGUm5XnoknrnQSGfZKTzW97iu0UwpN5tEx1qhlycsXiz4PTtVIAjcLyJxOQsqDNgMnW7RbJKgRwWX/OREg783P4XPe7Hzggnqao/xtwKbGF2hlfiBKDz/odIa9kLsOG0rRsnH3AT5TH+mDlOQGj7xwyk59dyUSpEdQ9xmaOsDd2k="
    # AWS_SECRET_ACCESS_KEY=[secure]
    - secure: "LMH8kMya1609DYOO0ElAwtDjSS8R57F/9C4bU6AbZNeUzSLWzMcpXd7VsYxk/eDXD5ZDo2bUGCRNl1rZ903CzR2lpMz6kgmr3XzMUPARKaI9UVIYNlLBDerEA1Tz6qUzQHYOM6AEDR6b4P1AeSYaEi7PKBpxvbWAk7xIpu5mOreCcmIa2T2X+4uNDmuCRcwoekyHeieFa8aex+lNpF4C20d+kGYkLElRynlQ8PyKYMqNC7vEeBchQ9Z0c8bqZl3QknzNDCFsD+WglEF5eIzorB280XSrf7vLZwvZCxjxITwOax04i6/qon7NONCOkg+a2fCSA4FowsBw8zSp6fH8Is8DVods94egMMGO6ahV02z2VwC8wEeQzUlAyINtmdWBgMiNSBg/Pjtab8Yvq3qqQo/7jlQgv1Ro7hi6FTmqjwu4C0e34Tfx19ZWSE+gQMBPEyMgad3HapamIgjtcl6MIPrQHFSTd/5b8Db+8c8UKVUhNK0rzWqfg7B/nDhmLc5MN8J5odfVt6TbNAsiy3BRW3po2b1dBbwxuO5Wv3eMHpEl0CtK4E6PO9XhLJ7iOx8MoRX4bZFTDtNh1si2d83ncyEI63CuOCXfTFqS+PFFGUwS3Mm9qDAqwnU1UDwd6kusztdknP/JwvUXp59v5VmE25BhTY8xU3o7XcDaW1ZDeXQ="

stage: "Run Unit Tests :clipboard:"
node_js:
  - 6
  - 8
before_install:
  - bash bin/travis-init.sh
script:
  - recink run unit -c recink-codeclimate -c recink-snyk
